### ISSUE TITLE
Unfortunately not working in 2018.3.0f2 .. linker error

### ISSUE THREAD

**Issue by smhk** [keijiro/TextureUpdateExample#4]
Thanks for this great example, but in Xcode

```
Undefined symbols for architecture arm64:
  "_GetTextureUpdateCallbackV2", referenced from:
      _Test_GetTextureUpdateCallbackV2_m3F68409646DD6E2A753FBD6D8277662808E892ED in Bulk_Assembly-CSharp_0.o
      _Test_Update_m51F75E0F25A98CAA4426F069A4E0EC7068A8C00E in Bulk_Assembly-CSharp_0.o
     (maybe you meant: _Test_GetTextureUpdateCallbackV2_m3F68409646DD6E2A753FBD6D8277662808E892ED)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Thanks ...

**Comment by keijiro** [comment]
Thanks for pointing it out. I just forgot update MacOS and iOS plugin code/binary. Please check out the latest update. It works on them now.

**Comment by smhk** [comment]
Master T ...

OMG.  You will never know how helpful this is.   Another masterpiec, thank you so much!

And thanks for that linker fix!

Thank you so much !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
